# Generated by Django 2.0.13 on 2019-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_person_fav_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
